libraryproject/books/urls.py
from django.urls import path

from books import views

app_name = "books"
urlpatterns = [
   # path("", views.login_view, name="login_view"),
    #path("logout/", views.logout_view, name="logout"),
    #path("login/", views.login_view, name="login_view"),
    #path("logout/", views.logout_view, name="logout_view"),
    path("create_user/", views.create_user, name="create_user"),
    path("", views.index, name="index"),  # Ruta inicial que requiere autenticación
    path("<int:book_id>/", views.details, name="details"),
    path("authors/", views.authors, name="authors"),
    path("authors/<int:author_id>/", views.authors_details, name="authors_details"),
    path("authors/add_author/", views.add_author, name="add_author"),
    path("genres/", views.genres, name="genres"),
    path("genres/<int:genre_id>/", views.genres_details, name="genres_details"),
    path("add_book/", views.add_book, name="add_book"),
    path("recent_books/", views.recent_books, name="recent_books"),
]

libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("books.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

libraryproject/books/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(blank=True, null=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ManyToManyField(Author, related_name='books')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='books_genre')
    publish_date = models.DateField()
    summary = models.TextField()

    def __str__(self):
        return f'{self.title}'

libraryproject/books/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from datetime import date
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from books.models import Book, Author, Genre
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    books_list = Book.objects.all()
    context = {
        'books_list': books_list
    }
    return render(request, "books/index.html", context)

@login_required
def details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, "books/details.html", {'book': book})

@login_required
def authors(request):
    authors = Author.objects.all()
    context = {
        'authors': authors
    }
    return render(request, "books/authors.html", context)

@login_required
def authors_details(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    books_list = author.books.all()
    return render(request, "books/authors_details.html", {'author': author, 'books_list': books_list})

@login_required
def add_author(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        birth_date = request.POST['birth_date']
        Author.objects.create(first_name=first_name, last_name=last_name, birth_date=birth_date)
        return HttpResponseRedirect(reverse("books:authors"))
    return render(request, "books/add_authors.html")

@login_required
def genres(request):
    genres = Genre.objects.all()
    lista_genero_libros = []

    for genre in genres:
        numbooks = genre.books_genre.count()
        lista_genero_libros.append((genre, numbooks))

    context = {
        'lista_genero_libros': lista_genero_libros,
    }
    return render(request, "books/genres.html", context)


@login_required
def genres_details(request, genre_id):
    genre = get_object_or_404(Genre, pk=genre_id)
    books_list = genre.books_genre.all()
    context = {
        'genre': genre,
        'books_list': books_list
    }
    return render(request, "books/genres_details.html",context)

@login_required
def add_book(request):

    authors_list = Author.objects.all()
    genre_list = Genre.objects.all()

    if request.method == "POST":

        title = request.POST.get('title')
        author_id = request.POST.get('author')
        genre_id = request.POST.get('genre')
        published_date = request.POST.get('published_date')
        summary = request.POST.get('summary')

        author = get_object_or_404(Author, pk=author_id)
        genre = get_object_or_404(Genre, pk=genre_id)

        book = Book.objects.create(title=title,genre=genre,publish_date=published_date,summary=summary)
        book.author.add(author)
        return HttpResponseRedirect(reverse("books:index"))

    context = {
        'authors_list': authors_list,
        'genre_list': genre_list,
    }
    return render(request, "books/add_books.html", context)

@login_required
def recent_books(request):
    hoy = date.today()
    hace_5_años = date(hoy.year - 5, hoy.month, hoy.day)

    # Filtra los libros publicados después de esa fecha
    recent_books_list = Book.objects.filter(publish_date__gte=hace_5_años)

    context = {
        'recent_books_list': recent_books_list,
    }
    return render(request, "books/recent_books.html", context)


def login_view(request):
   if request.method == "POST":
       username = request.POST["username"]
       password = request.POST["password"]
       user = authenticate(request, username=username, password=password)
       if user is not None:
           login(request, user)
           return HttpResponseRedirect(reverse("books:index"))
   return render(request, "books/login_view.html")

def logout_view(request):
   logout(request)
   return HttpResponseRedirect(reverse("books:login_view"))

def create_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        password_repeat = request.POST["password_repeat"]

        if password == password_repeat:
            user = User.objects.create_user(username, email, password)
            user.save()
            return HttpResponseRedirect(reverse("books:login_view"))
        else:
            error = True
            context = {
                'error': error
            }
            return render(request, "books/create_user.html", context)

    return render(request, "books/create_user.html")

libraryproject/books/templates/books/add_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Añadir Authors</title>
</head>
<body>
    <form method="post" action="{% url "books:add_author" %}">
        {% csrf_token %}
        <label for="first_name">Nombre:</label>
        <input type="text" id="first_name" name="first_name" required>
        <label for="last_name">Apellidos:</label>
        <input type="text" id="last_name" name="last_name" required>
        <label for="birth_date">Fecha de Nacimiento:</label>
        <input type="date" id="birth_date" name="birth_date">
        <input type="submit" value="Agregar" >
    </form>
</body>
</html>

libraryproject/books/templates/books/add_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Añadir Books</title>
</head>
<body>
    <h1>Añadir un nuevo libro</h1>
    <form method="post" action="{% url 'books:add_book' %}">
        {% csrf_token %}

        <label for="title">Título:</label>
        <input type="text" id="title" name="title" required><br>

        <h3>Autores:</h3>
        {% if authors_list %}
            <select name="author" id="author" required>
                <option value="" disabled selected>Selecciona un autor</option>
                {% for author in authors_list %}
                    <option value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
                {% endfor %}
            </select>
        {% else %}
            <p>No hay autores disponibles.</p>
        {% endif %}

        <h3>Géneros:</h3>
        {% if genre_list %}
            <select name="genre" id="genre" required>
                <option value="" disabled selected>Selecciona un género</option>
                {% for genre in genre_list %}
                    <option value="{{ genre.id }}">{{ genre.name }}</option>
                {% endfor %}
            </select>
        {% else %}
            <p>No hay géneros disponibles.</p>
        {% endif %}
    
    <br>

        <label for="published_date">Fecha de publicación:</label>
        <input type="date" id="published_date" name="published_date" required><br>
    <br>
        <label for="summary">Resumen:</label>
        <textarea name="summary" id="summary" required></textarea><br>

        <input type="submit" value="Agregar">
    </form>
</body>
</html>

libraryproject/books/templates/books/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
<h1>Authors</h1>
<p>Si quieres añadir nuevos autores <a href="{% url 'books:add_author' %}">pincha aquí</a></p>
    {% if authors %}
        <ul>
        {% for author in authors %}
            <li><a href="{% url 'books:authors_details' author.id %}">{{ author.first_name }} {{ author.last_name }}  
            </a></li> {% endfor %}
        </ul>
    {% else %}
        <p>No Authors are available.</p>
    {% endif %}
</body>
</html>

libraryproject/books/templates/books/authors_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DetallesAutor</title>
</head>
<body>
    <h1>Detalles del Autor</h1>
    <h2>Nombre Completo</h2>
        <h3>{{ author.first_name }} {{ author.last_name }}</h3>
    <h2>Fecha de nacimiento</h2>
        <h3>{{ author.birth_date }}</h3>
    <h2>Libros publicados</h2>
    <ul>
        {% for book in books_list %}
    	    <li>{{ book.title }}</li>
        {% endfor %}  
    </ul>
</body>
</html>

libraryproject/books/templates/books/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp</title>
</head>
<body>
    <form method="post" action="{% url "books:create_user" %}">
        {% csrf_token %}
        {% if error %}
        	<p>Las contraseñas deben coincidir</p>
        {% endif %} 
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br> <br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br> <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br> <br>
        <label for="password_repeat">Confirm Password:</label>
        <input type="password" id="password_repeat" name="password_repeat" required>
        <br> <br>
        <input type="submit" value="Crear Usuario" >
    </form>
</body>
</html>

libraryproject/books/templates/books/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DetallesLibro</title>
</head>
<body>
    <h1>Detalles del libro</h1>
    <h2> {{ book.title }}</h2>
    <h2>Author</h2>
    <ul>
        {% for author in book.author.all %}
    	    <li>{{ author }}</li>
        {% endfor %}  
    </ul>
    <h2>Genre</h2>
    <h3>{{ book.genre }}</h3>
    <h2>Publish Date</h2>
    <h3>{{ book.publish_date }}</h3>
    <h2>Summary</h2>
    <p>{{ book.summary }}</p>
</body>
</html>

libraryproject/books/templates/books/genres.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genres</title>
</head>
<body>
<h1>Genres</h1>
    {% if lista_genero_libros %}
        <ul>
        {% for genre, numbooks in lista_genero_libros %}
            <li>
                <a href="{% url 'books:genres_details' genre.id %}">
                    {{ genre.name }} ( {{ numbooks }} )
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No genres are available.</p>
    {% endif %}
</body>
</html>

libraryproject/books/templates/books/genres_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DetallesGenero</title>
</head>
<body>
    <h1>Detalles de Género</h1>
    <h2>Nombre</h2>
        <h3>{{ genre.name }}</h3>
    <h2>Libros</h2>
    <ul>
        {% for book in books_list %}
    	    <li>{{ book.title }}</li>
        {% endfor %}  
    </ul>
</body>
</html>

libraryproject/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PáginaPrincipal</title>
</head>
<body>
    <h1>Books</h1>
    {% if books_list %}
        <ul>
        <p>Si quieres añadir un libro <a href="{% url 'books:add_book' %}">pincha aquí</a></p>
        {% for book in books_list %}
            <li><a href="{% url 'books:details' book.id %}">{{ book.title }}:
                {% for author in book.author.all %}
                    {{ author }}
                {% endfor %}
            </a></li> {% endfor %}
        </ul>
        <button><a href="{% url 'books:recent_books' %}">Lista de libros publicados recientes</a></button>
        <button><a href="{% url 'books:authors' %}">Lista de autores</a></button>
         <button><a href="{% url 'books:genres' %}">Lista de géneros</a></button>
        <br> <br>
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <input type="submit" value="Logout">
        </form>
    {% else %}
        <p>No books are available.</p>
    {% endif %}
</body>
</html>

libraryproject/books/templates/books/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Iniciar Sesión</h1>
    <form method="post" action="{% url "books:login" %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <input type="submit" value="Iniciar Sesión" >
    </form>
</body>
</html>

libraryproject/books/templates/books/login_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{% url "books:login_view" %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br> <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br> <br>
        <input type="submit" value="Iniciar Sesión" >
    </form>
    <p>Si no tienes cuenta todavía  <a href="{% url 'books:create_user' %}">pincha aquí</a></p>

</body>
</html>

libraryproject/books/templates/books/recent_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Libros recientes</title>
</head>
<body>
    <h1>Libros publicados en los últimos 5 años</h1>
    {% if recent_books_list %}
        <ul>
            {% for book in recent_books_list %}
                <li>
                    <strong>{{ book.title }}</strong> - Publicado el {{ book.publish_date }}<br>
                    Autor(es):
                    {% for author in book.author.all %}
                        {{ author.first_name }} {{ author.last_name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}<br>
                    Género: {{ book.genre.name }}<br>
                    Resumen: {{ book.summary }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay libros publicados en los últimos 5 años.</p>
    {% endif %}
</body>
</html>